name: stdlibc
description: |
  C Standard Library - FFI bindings to the GNU C Library on Linux, and the BSD
  C Library on macOS.
homepage: https://github.com/ubuntu-flutter-community/stdlibc.dart
repository: https://github.com/ubuntu-flutter-community/stdlibc.dart
issue_tracker: https://github.com/ubuntu-flutter-community/stdlibc.dart/issues
version: 0.1.5

environment:
  sdk: ^3.0.0

platforms:
  linux:
  macos:

dependencies:
  collection: ^1.16.0
  ffi: ^2.1.4
  meta: ^1.7.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.11
  ffigen: ^18.1.0
  lints: ^5.1.1
  macro_builder:
    path: tool/macro_builder
  test: ^1.16.0
