name: glibc
description: Glibc - The GNU C Library for Dart

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  ffi: ^1.1.2
  meta: ^1.7.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.8
  ffigen: ^4.1.3
  lints: ^1.0.0
  macro_builder:
    path: tool/macro_builder
  test: ^1.16.0
