name: macro_builder
publish_to: 'none'

environment:
  sdk: '<4.0.0'

dependencies:
  analyzer: ^5.0.0
  build: ^2.2.1
  code_builder: ^4.1.0
  dart_style: ^2.2.2
  glob: ^2.0.2
  path: ^1.8.1

dev_dependencies:
  lints: ^2.0.0
